name: Publish to npm

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for .npmrc files
        run: find . -name .npmrc; cat ~/.npmrc || echo "No global .npmrc"

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Print npm config
        run: npm config list
      
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
